CI.YAML fixing

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -32,16 +32,25 @@ jobs:
           echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
 
       - name: Run mlflow project
-        env:
-          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
-          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
-          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/House-Rent-Prediction.mlflow
         run: |
           cd MLProject
-          RUN_NAME=ci-${{ github.run_id }}
-          mlflow run . --env-manager=local --run-name $RUN_NAME
-          echo "RUN_NAME=$RUN_NAME" >> $GITHUB_ENV
+          mlflow run . --env-manager=local > mlflow_execution.log 2>&1
+          cat mlflow_execution.log
       
+      - name: Extract RUN_ID
+        run: |
+          RUN_ID=$(grep -oE '[a-f0-9]{32}' MLProject/mlflow_execution.log | head -n 1)
+          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+          echo "Berhasil mengekstrak RUN_ID: $RUN_ID"
+      
+      - name: Validate RUN_ID
+        run: |
+          if [ -z "$RUN_ID" ]; then
+            echo "ERROR: RUN_ID tidak ditemukan di log!"
+            cat mlflow_output.log
+            exit 1
+          fi
+
       - name: Resolve MLflow RUN_ID from run name
         env:
           MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
@@ -75,15 +84,6 @@ jobs:
           MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
         run: |
           mlflow artifacts list --run-id ${{ env.RUN_ID }}
-
-      - name: Download MLflow model artifact
-        env:
-          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/House-Rent-Prediction.mlflow
-          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
-          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
-        run: |
-          mkdir -p mlflow_artifacts
-          mlflow artifacts download --run-id ${{ env.RUN_ID }} --artifact-path model --dst-path mlflow_artifacts
 
       - name: Commit MLflow artifacts to repo
         run: |
